add string fuzzing
DataDog/dd-native-appsec-js pull request #45
Opened 2022-02-08 10:44 UTC by vdeturckheim

### What does this PR do?

### Motivation

### Additional Notes

### Describe how to test your changes

### Checklist

- [ ] The CHANGELOG.md has been updated
- [ ] Unit tests have been updated and pass
- [ ] If known, an appropriate milestone has been selected

2022-02-08 13:40 UTC, simon-id requested changes

2022-02-08 13:40 UTC, simon-id commented on test/fuzz.js
> +  assert(!!r1)
`!!` is redundant. From the docs: `Tests if value is truthy. It is equivalent to assert.equal(!!value, true, message).`

2022-02-08 13:40 UTC, simon-id commented on test/fuzz.js
> +      it(`should handle the string ${str}`, () => {
Can we only print the string if it fails instead ? I feel like this is going to be annoying otherwise.

2022-02-08 13:40 UTC, simon-id commented on test/fuzz.js
> +  } catch (_) {
We run on node >=12
```suggestion
  } catch {
```

2022-02-09 09:36 UTC, vdeturckheim commented on test/fuzz.js
> +  assert(!!r1)
```suggestion
  assert(r1)
```

2022-02-09 09:36 UTC, vdeturckheim commented on test/fuzz.js
> +  assert(!!r1.data)
```suggestion
  assert(r1.data)
```

2022-02-09 09:43 UTC, vdeturckheim commented on test/fuzz.js
> +  } catch {
```suggestion
  } catch(_) {
```

2022-02-09 13:24 UTC, vdeturckheim commented on test/fuzz.js
> +  } catch(_) {
```suggestion
  } catch (_) {
```
```suggestion
  } catch(_) {
```

2022-02-15 09:57 UTC, simon-id approved these changes

2022-02-15 09:58 UTC, merged