Update libddwaf to 1.5.1
DataDog/dd-native-appsec-js pull request #68
Opened 2022-11-17 08:25 UTC by CarlesDD

### What does this PR do?

[](https://github.com/DataDog/libddwaf/blob/master/UPGRADING.md)

### Motivation

### Additional Notes

### Describe how to test your changes

### Checklist

- [ ] The CHANGELOG.md has been updated
- [ ] Unit tests have been updated and pass
- [ ] If known, an appropriate milestone has been selected

2022-11-17 12:45 UTC, simon-id commented
Pretty sure we need the `ddwaf_update_rule_data` feature for ip blocking.

2022-11-17 13:18 UTC, simon-id commented on src/main.cpp
>    }
I think `data` can be moved directly into the `DDWAF_MATCH` block
```suggestion
```

2022-11-17 13:18 UTC, simon-id commented on src/main.cpp
> +    res.Set("status", Napi::String::New(env, "match"));
```suggestion
    res.Set("status", Napi::String::New(env, "match"));
    res.Set("data", Napi::String::New(env, result.data));
```

2022-11-17 13:44 UTC, simon-id commented
Also you missed a `action` -> `status` in the test file line 235

2022-11-17 13:52 UTC, uurien commented on src/main.cpp
> +    for (uint32_t i = 0; i < result.actions.size; ++i) {
`result.actions` has always a value? Can it be `nullptr` and create `SEGFAULT` here?

2022-11-17 14:15 UTC, uurien commented on src/main.cpp
> +    for (uint32_t i = 0; i < result.actions.size; ++i) {
Yes, it looks fine

2022-11-22 11:53 UTC, CarlesDD commented on binding.gyp
> +        "libraries": ["Ws2_32.lib"],
Windows build was failing due to some missing external symbols.

`ddwaf_static.lib(ip_utils.obj) : error LNK2001: unresolved external symbol __imp_inet_pton`

2022-11-22 13:12 UTC, simon-id commented on binding.gyp
> +        "libraries": ["Ws2_32.lib"],
Right ok it's from the waf introducing the ip_utils thing make sense :+1:

2022-11-22 15:03 UTC, simon-id requested changes

2022-11-22 15:03 UTC, simon-id commented on test/index.js
> +    assert.strictEqual(result.actions[0], 'block')
```suggestion
    assert.deepStrictEqual(result.actions, ['block'])
```

2022-11-23 10:23 UTC, simon-id approved these changes

2022-11-23 10:24 UTC, simon-id commented on package.json
> +  "version": "2.0.0",
This is done automatically by `npm version major`

2022-11-23 13:39 UTC, merged